# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OktaRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OktaRN

  target 'OktaRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OktaRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OktaRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OktaRN-tvOS

  target 'OktaRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
